[DDOS-401] | Refactor AlamofireSessionRenewer using swift concurrency
dashdevs/AlamofireSessionRenewer pull request #10
Opened 2024-11-08 10:25 UTC by VolodymyrYatskanychItomych

# Description

BREAKING CHANGE: refactor AlamofireSessionRenewer using swift concurrency

# Task

[Task link](https://dashdevs.atlassian.net/browse/DDOS-401)

2024-11-12 19:10 UTC, yakovshkolnikov requested changes

2024-11-12 19:10 UTC, yakovshkolnikov commented on Sources/AlamofireSessionRenewer/AlamofireSessionRenewer.swift
>  /// This class is responsible for authentication credentials renewing process
nit: let's replace the comment with:
```suggestion
/// That actor is responsible for authentication credentials renewing process
```

2024-11-12 19:10 UTC, yakovshkolnikov commented on Sources/AlamofireSessionRenewer/AlamofireSessionRenewer.swift
>      /// Queue which stores requests to retry
nit: that comment isn't accurate anymore. Let's replace it with:
```suggestion
    /// An array which stores closures to retry requests after updating credentials
```

2024-11-12 19:10 UTC, yakovshkolnikov commented on Sources/AlamofireSessionRenewer/AlamofireSessionRenewer.swift
> +            let underlyingError = error.asAFError?.underlyingError as! NSError
Crash if `asAFError` is nil, let's keep `underlyingError` optional

2024-11-12 19:10 UTC, yakovshkolnikov commented on Sources/AlamofireSessionRenewer/AlamofireSessionRenewer.swift
> +            let isempty = await isCredentialEmpty()
nit
```suggestion
            let isEmpty = await isCredentialEmpty()
```

2024-11-12 19:10 UTC, yakovshkolnikov commented on Sources/AlamofireSessionRenewer/AlamofireSessionRenewer.swift
> +            let domain = await underlyingError.domain
nit: I would use `underlyingErrorDomain` name instead

2024-11-12 19:10 UTC, yakovshkolnikov commented on Example/Tests/ExampleTests.swift
> +        XCTAssertEqual(response?.response?.statusCode, MockAuthenticationFailureCode)
In the original test `error?.code` was checked instead, why it's replaced with response status code?

2024-11-12 19:10 UTC, yakovshkolnikov commented on Example/Tests/ExampleTests.swift
> +        let firstResponse = await sessionManager?.request(with: testFirstUrlRequestInfo)
Previous test was running two requests in parallel, now second request will be executed only after the first one. The proper way to test that is to use async let:
```
async let firstRequest = sessionManager?.request(with: testFirstUrlRequestInfo)
async let secondRequest = sessionManager?.request(with: testSecondUrlRequestInfo)
let firstResponse = await firstRequest?.response
let secondResponse = await secondRequest?.response
```

2024-11-12 19:10 UTC, yakovshkolnikov commented on Example/Tests/ExampleTests.swift
> +        XCTAssertEqual(response.response?.statusCode, MockAuthenticationFailureCode)
Same question here, why error.code is replaced with response status code?

2024-11-12 19:10 UTC, yakovshkolnikov commented on Example/Tests/ExampleTests.swift
> +        let responses = await withTaskGroup(of: (Int, DataResponse<Data?, AFError>?).self) { group in
Great usage of TaskGroup 👍

2024-11-14 10:05 UTC, VolodymyrYatskanychItomych commented on Example/Tests/ExampleTests.swift
> +        XCTAssertEqual(response?.response?.statusCode, MockAuthenticationFailureCode)
This is because we return `DataResponse<Data?, AFError>` instead of `DataRequest` in response now

2024-11-14 17:34 UTC, yakovshkolnikov approved these changes

2024-11-14 17:34 UTC, yakovshkolnikov commented on Sources/AlamofireSessionRenewer/AlamofireSessionRenewer.swift
> +            let underlyingErrorDomain = await underlyingError?.domain // updated variable name
What does `updated variable name` mean?

2025-09-14 19:32 UTC, yakovshkolnikov approved these changes

2025-09-14 19:34 UTC, merged